### PR TITLE
Reckless generalization

### PR DESCRIPTION
**Pull request by drdeaton**
> [!WARNING]
> This PR includes breaking changes, which intentionally break functionality. As such, using a version of ReveilLib built off of this version *will* break code written for older versions.

Generalizes the reckless controller for use in other parts of the code.
- Improved reckless controller code by a lot
- Renamed old path segment type to PilonsSegment for better attribution
- Added new Call and Await segments

Still needs:
- Documentation
- Code review :)

### CODE REVIEW

**Review by Jeremy924 — COMMENTED** [review]
Are you missing a break statement for the brake status in reckless.cc? 

```C++
...
    case SegmentStatusType::BRAKE:
      // Check if we havent started braking yet
      if (brake_time == -1) {
        chassis->set_brake_harsh();
        chassis->stop();
        brake_time = pros::millis();
/**********************************break here?**********************************/
      }
      // Check if enough time has elapsed to stop braking
      // If enough time has passed then it will just proceed as if it recieved a
      // NEXT
      else if (pros::millis() <= brake_time + 250)
        break;
    // Just like brake but without the braking
    case SegmentStatusType::NEXT:
      chassis->set_brake_coast();
...
```
If I understand it correctly, then wouldn't fall through to the Next segment status and then switch to the next segment?

**Comment by drdeaton** [comment]
@Jeremy924 good catch, I think you're right, let me check on that

**Review by Jeremy924 — APPROVED** [review]
It looks good to me. The only minor issue that I noticed is that at least one of your comments are incomplete.

**Comment by drdeaton** [comment]
All seems good, cppcheck passed, merging

**Pull request merged**
